# Generated by Django 5.2.5 on 2025-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cliente_itemvenda_perfil_venda_itemvenda_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rua'),
        ),
    ]
